mode: 'train'
ARCHITECTURE:
    name: 'ResNeXt101_64x4d'

pretrained_model: ""
model_save_dir: "./output/"
classes_num: 20
total_images: 82213
save_interval: 1
validate: True
valid_interval: 1
epochs: 30
topk: 5
image_shape: [3, 128, 128]

use_mix: False
ls_epsilon: -1

LEARNING_RATE:
    function: 'Piecewise'          
    params:                   
        lr: 0.025
        decay_epochs: [10, 18, 24]
        gamma: 0.1 

OPTIMIZER:
    function: 'Momentum'
    params:
        momentum: 0.9
    regularizer:
        function: 'L2'
        factor: 0.000150

TRAIN:
    batch_size: 256
    num_workers: 4
    file_list: "/media/gujingxiao/f577505e-73a2-41d0-829c-eb4d01efa827/BaiduStar2020/classfication/train_list.txt"
    data_dir: "/media/gujingxiao/f577505e-73a2-41d0-829c-eb4d01efa827/BaiduStar2020/classfication/train/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - RandCropImage:
            size: 128
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:

VALID:
    batch_size: 64
    num_workers: 4
    file_list: "/media/gujingxiao/f577505e-73a2-41d0-829c-eb4d01efa827/BaiduStar2020/classfication/val_list.txt"
    data_dir: "/media/gujingxiao/f577505e-73a2-41d0-829c-eb4d01efa827/BaiduStar2020/classfication/train/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            resize_short: 128
        - CropImage:
            size: 128
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:
